---
all:
  hosts: 
    cvaas: 
      ansible_host: www.arista.io
      ansible_user: cvaas
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: False
      ansible_network_os: eos
      ansible_httpapi_port: 443
  children:
    PF_NETWORK:
      vars:
        ansible_user: arista
        ansible_password: arista1234
        ansible_connection: httpapi
        ansible_network_os: eos
        ansible_httpapi_use_ssl: true
        ansible_httpapi_validate_certs: false
        ansible_httpapi_port: 443
        ansible_become: yes
        ansible_become_method: enable
      children:
        TENANT_AVTS:
          children:
            REGIONS:
              children:
                REGION1:
                  children:
                    REGION1_PATHFINDERS:
                      hosts:
                        RR1:
                        RR2:
                    REGION1_EDGE:
                      children:
                        SITE11:
                          hosts:
                            Edge10:
                        SITE12:
                          hosts: 
                            Edge12:
                        SITE13:
                          hosts:
                            Edge13:
                        SITE14:
                          hosts:
                            Edge14:
                        REGION1_TRANSIT:
                          hosts:
                            P10:
                            P11:
                REGION2:
                  children:
                    REGION2_PATHFINDERS:
                      hosts:
                        RR3:
                        RR4:
                    REGION2_EDGE:
                      children:
                        SITE21:
                          hosts:
                            Edge20:
                        SITE22:
                          hosts: 
                            Edge22:
                        SITE23:
                          hosts:
                            Edge23:
                        SITE24:
                          hosts:
                            Edge24:
                        REGION2_TRANSIT:
                          hosts:
                            P20:
                            P21: